// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3bvv4NXUVOC79a2HSea18oBgmYowAjQg',
    appId: '1:718489800812:web:c7bed3e5259501ecce4849',
    messagingSenderId: '718489800812',
    projectId: 'deeon-5fcb4',
    authDomain: 'deeon-5fcb4.firebaseapp.com',
    storageBucket: 'deeon-5fcb4.firebasestorage.app',
    measurementId: 'G-C00GSXP2J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKjyqsOcvLQZBglSD12ky62Sqb4_73MfQ',
    appId: '1:718489800812:android:0a93b8f96b893197ce4849',
    messagingSenderId: '718489800812',
    projectId: 'deeon-5fcb4',
    storageBucket: 'deeon-5fcb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvRwjqI8vdoby_G4DQu1IOsYM_l5wbrXI',
    appId: '1:718489800812:ios:13122c787a6386bdce4849',
    messagingSenderId: '718489800812',
    projectId: 'deeon-5fcb4',
    storageBucket: 'deeon-5fcb4.firebasestorage.app',
    iosBundleId: 'com.example.deeon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvRwjqI8vdoby_G4DQu1IOsYM_l5wbrXI',
    appId: '1:718489800812:ios:13122c787a6386bdce4849',
    messagingSenderId: '718489800812',
    projectId: 'deeon-5fcb4',
    storageBucket: 'deeon-5fcb4.firebasestorage.app',
    iosBundleId: 'com.example.deeon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3bvv4NXUVOC79a2HSea18oBgmYowAjQg',
    appId: '1:718489800812:web:6e1e097c8bef97f7ce4849',
    messagingSenderId: '718489800812',
    projectId: 'deeon-5fcb4',
    authDomain: 'deeon-5fcb4.firebaseapp.com',
    storageBucket: 'deeon-5fcb4.firebasestorage.app',
    measurementId: 'G-Z6T39ZSYBW',
  );
}
